# name=input("enter your full name :")
# print(len(name))
# res=name.find('k')
# print(res)
# re=name.rfind("k")
# print(re)
# r=name.capitalize()
# print(r)
# name=name.upper()
# print(name)
# name=name.lower()
# print(name)
# res=name.isdigit()
# print(res)
# res=name.isalpha()
# print(res)
# num=input("enter a number :")
# res=num.count("8")
# print(res)
# num=num.replace("8","0")
# print(num)
username = input('enter your username ')
if len(username) > 12 :
    print("invalid")
elif not  username.isalpha():
    print("invalid")
elif not username.find(" ") == -1:
    print("invalid")
else:
    print("valid")
